Sites/LoggingSolution.Portal/Controllers/ApplicationController.cs
using System.Linq;
using System.Threading.Tasks;
using LoggingSolution.Data;
using LoggingSolution.Portal.Dtos;
using LoggingSolution.Portal.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LoggingSolution.Portal.Controllers
{
    public class ApplicationController : Controller
    {
        private readonly LoggingDBContext _context;

        public ApplicationController(LoggingDBContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var applications = await _context.LogApplications
                .Select(x => new ApplicationDto
                {
                    Id = x.Id,
                    Name = x.Name
                })
                .ToListAsync();

            var vm = new ApplicationListViewModel
            {
                Applications = applications
            };

            return View("List", vm);
        }
    }
}

Sites/LoggingSolution.Portal/Controllers/CategoryController.cs
using System.Linq;
using System.Threading.Tasks;
using LoggingSolution.Data;
using LoggingSolution.Portal.Dtos;
using LoggingSolution.Portal.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LoggingSolution.Portal.Controllers
{
    public class CategoryController : Controller
    {
        private readonly LoggingDBContext _context;

        public CategoryController(LoggingDBContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var categories = await _context.LogCategories
                .Select(x => new CategoryListDto
                {
                    Id = x.Id,
                    Name = x.Name,
                    Application = new ApplicationDto
                    {
                        Id = x.Application.Id,
                        Name = x.Application.Name
                    },
                })
                .ToListAsync();

            CategoryListViewModel vm = new CategoryListViewModel
            {
                Categories = categories
            };

            return View("List", vm);
        }

        public async Task<IActionResult> List(int applicationId)
        {
            var categories = await _context.LogCategories
                .Where(x => x.ApplicationId == applicationId)
                .Select(x => new CategoryDto
                {
                    Id = x.Id,
                    Name = x.Name
                })
                .ToListAsync();

            categories.ForEach(x => x.ApplicationId = applicationId);

            CategoryListByAppViewModel vm = new CategoryListByAppViewModel
            {
                ApplicationId = applicationId,
                Categories = categories
            };

            return View("ListByApplication", vm);
        }
    }
}

Sites/LoggingSolution.Portal/Controllers/EntryController.cs
using System;
using System.Threading.Tasks;
using LoggingSolution.Portal.Services;
using LoggingSolution.Portal.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LoggingSolution.Portal.Controllers
{
    public class EntryController : Controller
    {
        private readonly LogEntryService _entryService;

        public EntryController(LogEntryService entryService)
        {
            _entryService = entryService;
        }

        public IActionResult Index()
        {
            return RedirectToAction(nameof(All));
        }

        public async Task<IActionResult> All()
        {
            var filter = new LogFilterViewModel
            {
                Start = DateTime.UtcNow.Date
            };

            var entries = await _entryService.GetEntriesByFilter(filter);
            var vm = new EntryListViewModel
            {
                MinDate = filter.Start,
                Entries = entries
            };

            return View("Index", vm);
        }

        public async Task<IActionResult> ForApplication(int applicationId)
        {
            var filter = new LogFilterViewModel
            {
                Start = DateTime.UtcNow.Date,
                ApplicationId = applicationId
            };

            var entries = await _entryService.GetEntriesByFilter(filter);
            var vm = new EntryListViewModel
            {
                ApplicationId = applicationId,
                MinDate = filter.Start,
                Entries = entries
            };

            return View("Index", vm);
        }

        public async Task<IActionResult> ForCategory(int categoryId)
        {
            var filter = new LogFilterViewModel
            {
                Start = DateTime.UtcNow.Date,
                CategoryId = categoryId
            };

            var entries = await _entryService.GetEntriesByFilter(filter);
            var vm = new EntryListViewModel
            {
                CategoryId = categoryId,
                MinDate = filter.Start,
                Entries = entries
            };

            return View("Index", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Filter([FromBody] LogFilterViewModel filter)
        {
            var entries = await _entryService.GetEntriesByFilter(filter);
            return PartialView("_ListPartial", entries);
        }

        public async Task<IActionResult> Exception(int id)
        {
            var exception = await _entryService.GetException(id);
            if (exception == null)
            {
                return NoContent();
            }

            return PartialView("_LogExceptionPartial", exception);
        }
    }
}

Sites/LoggingSolution.Portal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Portal</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />

    @RenderSection("Styles", required: false)
</head>
<body>
    <header id="header" class="mb-3">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow ">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Application" asp-action="Index">Applications</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Entry" asp-action="Index">Logs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
    @RenderSection("Modals", required: false)
</body>
</html>